### PR TITLE
Reworded potentially misleading description of initial connection to ref...

### PR DESCRIPTION
**Pull request by kenhunt**
Reworded potentially misleading description of initial connection to reflect that client.connect() establishes a connection to Respoke, not directly to another endpoint.

### CODE REVIEW

**Comment by pho3nixf1re** [comment]
:+1:

**Comment by erinspice** [comment]
establish a connection between the endpoints using -> establish a connection from each endpoint to Respoke using
sending a message is a simple matter -> sending a message to another endpoint is a simple matter

**Comment by erinspice** [comment]
establish a connection between the endpoints using -> establish a connection from each endpoint to Respoke using
sending a message is a simple matter -> sending a message to another endpoint is a simple matter

**Comment by erinspice** [comment]
establish a connection between the endpoints using -> establish a connection from each endpoint to Respoke using
sending a message is a simple matter -> sending a message to another endpoint is a simple matter

**Comment by erinspice** [comment]
establish a connection between the endpoints using -> establish a connection from each endpoint to Respoke using
sending a message is a simple matter -> sending a message to another endpoint is a simple matter

**Comment by erinspice** [comment]
establish a connection between the endpoints using -> establish a connection from each endpoint to Respoke using
sending a message is a simple matter -> sending a message to another endpoint is a simple matter

**Comment by erinspice** [comment]
establish a connection between the endpoints using -> establish a connection from each endpoint to Respoke using
sending a message is a simple matter -> sending a message to another endpoint is a simple matter

**Comment by erinspice** [comment]
Dammit, Github.

**Comment by erinspice** [comment]
Dammit, Github.

**Comment by ruffrey** [comment]
:+1: 

This is where having a hard 80 col limit is nice - for seeing diffs :)

**Comment by ruffrey** [comment]
Published!

**Pull request merged**
